services:
  bot-financeiro:
    build: .
    container_name: bot-financeiro
    ports:
      - "3006:3000"  # <--- ADICIONE ISSO se o painel precisar acessar o bot
    environment:
      - TZ=America/Recife
      - BOT_NOME=Financeiro
    volumes:
      - ./auth_financeiro:/app/auth_info
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"